nguage: node_js
node_js:
- 12.16.2
branches:
  only:
  - master
install:
  - npm install
  - npm run build
script:
- echo "build"
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
addons:
  ssh_known_hosts:
  - 139.196.51.218
after_success:
- chmod 600 ~/.ssh/id_rsa
- rsync -az --delete ./dist/* root@139.196.51.218:/usr/local/syb/nuxt
- rsync -az --delete .nuxt nuxt.config.js package.json root@139.196.51.208:/usr/local/syb/nuxt
- ssh root@139.196.51.218 -o StrictHostKeyChecking=no 'cd /usr/local/syb/syb-life/ && npm install && pm2 start npm --name "syb-life" -- run start'
